<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Movimentacao_model extends CI_Model
{

    public $table = 'movimentacao';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function soma_valor($valor, $mes, $ano){

        $this->db->select("SUM(valor) as total");
        $this->db->where("tipo =".$valor);
        $this->db->where("mes =". $mes);
        $this->db->where("ano = ".$ano);

        return $this->db->get($this->table)->result();
    }

    function soma_movimentacao_total($valor, $ano){

        $this->db->select("SUM(valor) as soma_total");
        $this->db->where("tipo =".$valor);
        $this->db->where("ano =".$ano);

        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tipo', $q);
	$this->db->or_like('dia', $q);
	$this->db->or_like('mes', $q);
	$this->db->or_like('ano', $q);
	$this->db->or_like('cat', $q);
	$this->db->or_like('descricao', $q);
	$this->db->or_like('valor', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('tipo', $q);
    	$this->db->or_like('dia', $q);
    	$this->db->or_like('mes', $q);
    	$this->db->or_like('ano', $q);
    	$this->db->or_like('cat', $q);
    	$this->db->or_like('descricao', $q);
    	$this->db->or_like('valor', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

   public function getMovimentacao($limit, $start = 0, $q = NULL){
        $this->db->select('m.*, c.nome AS nome_categoria');
        $this->db->from($this->table . ' as m');
        $this->db->join('categoria as c', 'm.cat = c.id');
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);

        return $this->db->get()->result();
    }

        // get data with limit and search
    function getView($limit, $start = 0, $q = NULL, $mes = NULL, $ano = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('ano', $mes);
        $this->db->where('mes', $ano);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Movimentacao_model.php */
/* Location: ./application/models/Movimentacao_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-29 23:21:51 */
/* http://harviacode.com */